CREATE SCHEMA "registry";
--> statement-breakpoint
CREATE TYPE "registry"."defibrillator_status" AS ENUM('working', 'maintenance', 'out_of_service');--> statement-breakpoint
CREATE TYPE "registry"."lora_device_status" AS ENUM('active', 'inactive', 'maintenance');--> statement-breakpoint
CREATE TABLE "registry"."defibrillator" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"is_mobile" boolean DEFAULT true NOT NULL,
	"status" "registry"."defibrillator_status" DEFAULT 'working' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "registry"."defibrillator" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "registry"."lora_device" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"defibrillator_id" uuid,
	"dev_eui" varchar(16) NOT NULL,
	"status" "registry"."lora_device_status" DEFAULT 'active' NOT NULL,
	"battery_percentage" integer,
	"latitude" double precision,
	"longitude" double precision,
	"last_transmission_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lora_device_dev_eui_unique" UNIQUE("dev_eui"),
	CONSTRAINT "lora_device_battery_range" CHECK ("registry"."lora_device"."battery_percentage" IS NULL OR "registry"."lora_device"."battery_percentage" BETWEEN 0 AND 100),
	CONSTRAINT "lora_device_latitude_range" CHECK ("registry"."lora_device"."latitude" IS NULL OR "registry"."lora_device"."latitude" BETWEEN -90 AND 90),
	CONSTRAINT "lora_device_longitude_range" CHECK ("registry"."lora_device"."longitude" IS NULL OR "registry"."lora_device"."longitude" BETWEEN -180 AND 180)
);
--> statement-breakpoint
ALTER TABLE "registry"."lora_device" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "registry"."registrant" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100),
	"phone" varchar(30) NOT NULL,
	"medical_training" varchar(100),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "registry"."registrant" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "registry"."defibrillator" ADD CONSTRAINT "defibrillator_owner_id_registrant_id_fk" FOREIGN KEY ("owner_id") REFERENCES "registry"."registrant"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registry"."lora_device" ADD CONSTRAINT "lora_device_owner_id_registrant_id_fk" FOREIGN KEY ("owner_id") REFERENCES "registry"."registrant"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registry"."lora_device" ADD CONSTRAINT "lora_device_defibrillator_id_defibrillator_id_fk" FOREIGN KEY ("defibrillator_id") REFERENCES "registry"."defibrillator"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "guest_can_create_defibrillator" ON "registry"."defibrillator" AS PERMISSIVE FOR INSERT TO "app_guest" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "admin_can_manage_defibrillators" ON "registry"."defibrillator" AS PERMISSIVE FOR ALL TO "app_authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "guest_can_create_lora_device" ON "registry"."lora_device" AS PERMISSIVE FOR INSERT TO "app_guest" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "admin_can_manage_lora_devices" ON "registry"."lora_device" AS PERMISSIVE FOR ALL TO "app_authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "guest_can_create_registrant" ON "registry"."registrant" AS PERMISSIVE FOR INSERT TO "app_guest" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "admin_can_manage_registrants" ON "registry"."registrant" AS PERMISSIVE FOR ALL TO "app_authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint

-- Both runtime roles may resolve objects in the registry schema, but neither
-- role may create or drop schema objects.
GRANT USAGE ON SCHEMA registry TO app_guest, app_authenticated;--> statement-breakpoint

-- Public registration can only provide identity/contact information. IDs are
-- generated by the API so related records can be inserted without granting
-- public SELECT access or weakening RLS.
GRANT INSERT (id, first_name, last_name, phone, medical_training)
ON registry.registrant TO app_guest;--> statement-breakpoint

-- A public registration may attach equipment, but it cannot choose operational
-- status or write telemetry fields such as battery and location.
GRANT INSERT (id, owner_id, is_mobile)
ON registry.defibrillator TO app_guest;--> statement-breakpoint
GRANT INSERT (id, owner_id, defibrillator_id, dev_eui)
ON registry.lora_device TO app_guest;--> statement-breakpoint

-- Authenticated accounts are administrators in this application. CRUD is
-- sufficient; deliberately omit TRUNCATE, REFERENCES, TRIGGER and schema DDL.
GRANT SELECT, INSERT, UPDATE, DELETE
ON registry.registrant, registry.defibrillator, registry.lora_device
TO app_authenticated;--> statement-breakpoint

-- Administrators may explicitly assign enum values during device management.
GRANT USAGE ON TYPE registry.defibrillator_status, registry.lora_device_status
TO app_authenticated;
